apiVersion: v2
name: hawtio-online-console-plugin
description: A Helm chart for installing the OpenShift Console plugin for HawtIO
type: application
version: 0.6.2
appVersion: 0.6.0
annotations:
  artifacthub.io/prerelease: "true"
keywords:
  - hawtio
  - camel
  - console
  - jmx
  - react
home: https://hawt.io
sources:
  - https://github.com/hawtio/hawtio-online-console-plugin.git
icon: https://hawtio.github.io/hawtio-charts/hawtio-console-plugin-logo.png
