apiVersion: v2
name: hawtio-online-console-plugin
description: A Helm chart for installing the OpenShift Console plugin for HawtIO
type: application
version: 0.4.0-alpha2
appVersion: 0.4.0-alpha2
keywords:
  - hawtio
  - camel
  - console
  - jmx
  - react
home: https://hawt.io
sources:
  - https://github.com/hawtio/hawtio-online-console-plugin.git
