apiVersion: v2
name: hawtio-online-console-plugin
description: A Helm chart for installing the OpenShift Console plugin for HawtIO
type: application
version: 0.6.3
appVersion: 0.6.0
kubeVersion: ">= 1.24.0"
annotations:
  artifacthub.io/prerelease: "true"
  charts.openshift.io/name: hawtio-online-console-plugin
keywords:
  - hawtio
  - camel
  - console
  - jmx
  - react
home: https://hawt.io
sources:
  - https://github.com/hawtio/hawtio-online-console-plugin.git
icon: https://hawtio.github.io/hawtio-charts/hawtio-console-plugin-logo.png
